export const ARITHMETIC_OPERATION_ADDITION = 'ADDITION';
export const ARITHMETIC_OPERATION_SUBTRACTION = 'SUBTRACTION';
export const ARITHMETIC_OPERATION_MULTIPLICATION = 'MULTIPLICATION';
export const ARITHMETIC_OPERATION_DIVISION = 'DIVISION';
